backend:
  name: git-gateway
  branch: main

media_folder: images/gallery
public_folder: images/gallery

collections:
  - name: gallery
    label: Gallery Photos
    folder: images/gallery
    create: true
    extension: jpg
    fields:
      - {label: Photo, name: title, widget: string}
      - {label: Image, name: body, widget: image}
